import { defineConfig } from 'vitest/config'

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    environment: 'node',
    include: ['actions/**/*.test.ts', 'lib/**/*.test.ts', 'types/**/*.test.ts', 'app/api/**/route.test.ts'],
    exclude: [
      'node_modules',
      '.next',
      'app/**/page.tsx',
      'app/**/layout.tsx',
      'app/**/loading.tsx',
      'app/**/error.tsx',
      'components',
      'hooks',
      'scripts',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      include: [
        'lib/auth/auth/auth.ts',
        'lib/auth/rateLimit/rateLimit.ts',
        'lib/auth/verificationToken/verificationToken.ts',
        'lib/auth/accountDeletion/accountDeletion.ts',
        'lib/auth/authConfig/authConfig.ts',
        'lib/utils/utils.ts',
        'lib/constants.ts',
        'lib/constants/limits.ts',
        'lib/db/collections/collections.ts',
        'lib/db/items/items.ts',
        'lib/r2.ts',
        'lib/fileValidation.ts',
        'types/db.ts',
        'actions/auth/Auth.ts',
        'actions/signIn/SignIn.ts',
        'actions/forgotPassword/ForgotPassword.ts',
        'actions/resetPassword/ResetPassword.ts',
        'actions/resendVerification/ResendVerification.ts',
        'actions/signInGithub/SignInGithub.ts',
        'actions/profile/Profile.ts',
        'actions/items/Items.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 70,
        statements: 80,
      },
    },
  },
})
