export const DEFAULT_RECENT_LIMIT = 10;
export const DEFAULT_FAVORITE_LIMIT = 10;
export const DEFAULT_SAMPLE_COUNT = 5;
export const DEFAULT_RECENT_COLLECTIONS_LIMIT = 5;
export const ITEMS_PER_PAGE = 21;
export const COLLECTIONS_PER_PAGE = 21;
export const DASHBOARD_COLLECTIONS_LIMIT = 6;
export const DASHBOARD_RECENT_ITEMS_LIMIT = 10;
